### ISSUE TITLE
Cijfer induwen na bewerking start geen nieuwe bewerking op, maar voegt cijfer aan resultaat toe

### ISSUE THREAD

**Issue by braekstuv** [salimakhayad/Rekenmachine#1]
Repro steps:
1. Voer een bewerking in (2 + 2)
2. Druk op =
3. druk een cijfer in (2)

expected: start een nieuwe bewerking (2)
actual: 42
![image](https://user-images.githubusercontent.com/11158784/62153240-6ce99800-b304-11e9-8e44-307ccf4bc023.png)

**Comment by salimakhayad** [comment]
Klopt, Het idee was om verder te kunnen werken met de output van de vorige bewerking zoals bij winforms :D
