### ISSUE TITLE
Foutieve bewerking

### ISSUE THREAD

**Issue by braekstuv** [salimakhayad/Rekenmachine#2]
9/0 => cannot divide by zero
![image](https://user-images.githubusercontent.com/11158784/62153368-b0440680-b304-11e9-8790-bc4e87e284fc.png)

**Comment by salimakhayad** [comment]
Nullcheck toegevoegd.
![image](https://user-images.githubusercontent.com/9267304/65373400-62e97300-dc7d-11e9-8cd2-b166da5488d5.png)
