### ISSUE TITLE
exception gethrowed

### ISSUE THREAD

**Issue by braekstuv** [salimakhayad/Rekenmachine#4]
Repro steps
Druk op +- zonder dat er een getal ingegeven werd

![image](https://user-images.githubusercontent.com/11158784/62153693-71fb1700-b305-11e9-97eb-60324c1e7a79.png)

**Comment by salimakhayad** [comment]
Fixed
![image](https://user-images.githubusercontent.com/9267304/65373713-20299a00-dc81-11e9-9c21-5f56abf73c35.png)
