### ISSUE TITLE
Meerdere click event handlers met soortgelijke implementatie

### ISSUE THREAD

**Issue by braekstuv** [salimakhayad/Rekenmachine#5]
Je kan deze soort klikevents verzamelen onder 1 enkel event, die gewoon de tekst van de knop doorgeven naar je bewerking
![image](https://user-images.githubusercontent.com/11158784/62154001-1bdaa380-b306-11e9-826d-960822c4a112.png)

**Comment by salimakhayad** [comment]
Cleaned up those functions! Florian :)
![image](https://user-images.githubusercontent.com/9267304/65373601-17849400-dc80-11e9-92ae-41a4abd62ad0.png)
