### ISSUE TITLE
Exception gethrowed

### ISSUE THREAD

**Issue by braekstuv** [salimakhayad/Rekenmachine#6]
Ingevoerde bewerking:
8/5^2
![image](https://user-images.githubusercontent.com/11158784/62154280-b1763300-b306-11e9-960c-46bc36e59895.png)

**Comment by salimakhayad** [comment]
- Zat een logiche fout in de code, dmv debugging gespot.
Opgelost Thx Florian.
![image](https://user-images.githubusercontent.com/9267304/65372483-434c4d80-dc71-11e9-859a-3527e8d6ae9b.png)
