### ISSUE TITLE
Input foutief opgevangen

### ISSUE THREAD

**Issue by braekstuv** [salimakhayad/Rekenmachine#7]
De laatst ingegeven bewerking zou degene moeten zijn die effectief gebruikt wordt

![image](https://user-images.githubusercontent.com/11158784/62154661-758f9d80-b307-11e9-9307-79492ed3aa7d.png)

**Comment by salimakhayad** [comment]
Not a valid Calculation Exept. added
![image](https://user-images.githubusercontent.com/9267304/65373473-4e59aa80-dc7e-11e9-9bff-5579f08a1558.png)

**Comment by salimakhayad** [comment]
Calculatie uitvoeren met de laatst ingevoerde operator (nog) niet functioneel
